[package]
name = "ua-parser-node"
version = "0.0.1-alpha.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Node bindings for the ua-parser (uap-rust) user-agent parser"
repository = "https://github.com/benasher44/ua-parser-node"

[build-dependencies]
napi-build = "2"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3", default-features = false, features = ["napi8"] }
napi-derive = "3"
ua-parser = "0.2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
mimalloc = { version = "0.1", default-features = false, optional = true }
jemallocator = { version = "0.5", default-features = false, optional = true }

[features]
default = []
allocator-mimalloc = ["dep:mimalloc"]
allocator-jemalloc = ["dep:jemallocator"]

[profile.release]
lto = true
strip = "symbols"
