/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * Which binding artifact the generated loader actually loaded: `'native'` for
 * a native addon, otherwise the `platformArchABI` of the WASI flavor. Every
 * flavor napi-rs can build is listed, because `NAPI_RS_NATIVE_LIBRARY_PATH`
 * can point the loader at a WASI artifact this package does not build itself.
 */
export declare const __napiBindingTarget: 'native' | 'wasm32-wasi' | 'wasm32-wasip1'

export declare function parseUserAgent(ua: string): UaResult

export interface UaResult {
  /** e.g. "Chrome", "Mobile Safari", "Firefox" */
  browser?: string
  /** major version only, e.g. "138" */
  browserVersion?: string
  /** e.g. "Mac OS X", "Windows", "iOS", "Android" */
  os?: string
  /** major version only, e.g. "10", "18" */
  osVersion?: string
}
